### ISSUE TITLE
Analysis tools are not fully validated

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#918]
Umbrella issue for validation of analysis tools, needs to be elaborated into a set of detailed issues

- [x] Create test suites for resource, latency, and safety analysis tools
- [ ] Create test for Weight Analysis (#1070)
- [ ] Create tests for resource budget analyses (#1072)
- [ ] Create tests for flow latency analysis (#1104)

parent of #1070, parent of #1072, parent of #1104
